echo;../galaxie --options tp://localhost/
echo;../galaxie --options tp://localhost/game
echo;../galaxie --options tp://nash@localhost/
echo;../galaxie --options tp://nash:password@localhost/
echo;../galaxie --options tp://nash:password@localhost:999/
echo;../galaxie --options tp://nash:password@localhost/game
echo;../galaxie --options tp://nash:password@localhost:999/game
echo;../galaxie --options tp://localhost:999/
echo;../galaxie --options tp://nash@localhost:999/
echo;../galaxie --options tp://nash@localhost:999/
echo;../galaxie --options tphttp://localhost/
echo;../galaxie --options tphttp://nash@localhost/
echo;../galaxie --options tphttp://nash:password@localhost/
echo;../galaxie --options tphttp://nash:password@localhost:999/
echo;../galaxie --options tphttp://localhost:999/
echo;../galaxie --options tphttp://nash@localhost:999/
echo;../galaxie --options tp+http://localhost/
echo;../galaxie --options tp+http://nash@localhost/
echo;../galaxie --options tp+http://nash:password@localhost/
echo;../galaxie --options tp+http://nash:password@localhost:999/
echo;../galaxie --options tp+http://localhost:999/
echo;../galaxie --options tp+http://nash@localhost:999/
echo;../galaxie --options tps://localhost/
echo;../galaxie --options tps://nash@localhost/
echo;../galaxie --options tps://nash:password@localhost/
echo;../galaxie --options tps://nash:password@localhost:999/
echo;../galaxie --options tps://localhost:999/
echo;../galaxie --options tps://nash@localhost:999/
echo;../galaxie --options tphttps://localhost/
echo;../galaxie --options tphttps://nash@localhost/
echo;../galaxie --options tphttps://nash:password@localhost/
echo;../galaxie --options tphttps://nash:password@localhost:999/
echo;../galaxie --options tphttps://localhost:999/
echo;../galaxie --options tphttps://nash@localhost:999/
echo;../galaxie --options tp+https://localhost/
echo;../galaxie --options tp+https://nash@localhost/
echo;../galaxie --options tp+https://nash:password@localhost/
echo;../galaxie --options tp+https://nash:password@localhost:999/
echo;../galaxie --options tp+https://localhost:999/
echo;../galaxie --options tp+https://nash@localhost:999/
