Document: galaxie
Title: Debian galaxie Manual
Author: <insert document author here>
Abstract: This manual describes what galaxie is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/galaxie/galaxie.sgml.gz

Format: postscript
Files: /usr/share/doc/galaxie/galaxie.ps.gz

Format: text
Files: /usr/share/doc/galaxie/galaxie.text.gz

Format: HTML
Index: /usr/share/doc/galaxie/html/index.html
Files: /usr/share/doc/galaxie/html/*.html

  
